### PR TITLE
MG-12-Create-enemy-graphics

### PR DESCRIPTION
**Pull request by misel-cucek**
Create graphics for enemy player.

### CODE REVIEW

**Comment by misel-cucek** [comment]
@bzorec @AnejBezjak how many enemies should we include I was thinking 1 - 3.

**Comment by misel-cucek** [comment]
@bzorec @AnejBezjak will possibly need a maze finish graphic... was thinking of a trophy.

**Review by bzorec — APPROVED** [review]
nice

**Comment by bzorec** [comment]
ye we can add how many enemies we just need to configure it

**Pull request merged**
